[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/success"
  to = "/"
  status = 200

[[redirects]]
  from = "/abandonment"
  to = "/"
  status = 200
